services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: secure
      PGDATA: /data/postgres
    ports:
      - '5332:5432'
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: